apiVersion: v1
kind: ServiceAccount
metadata:
  name: gh-actions-pf
  namespace: fy
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gh-actions-pf
  namespace: fy
rules:
  - apiGroups: [""]
    resources: ["pods"]
    resourceNames: ["db-postgresql-0"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["pods/portforward"]
    resourceNames: ["db-postgresql-0"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gh-actions-pf
  namespace: fy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gh-actions-pf
subjects:
  - kind: ServiceAccount
    name: gh-actions-pf
    namespace: fy
# TOKENNAME=`kubectl -n fy get serviceaccount/gh-actions-pf -o jsonpath='{.secrets[0].name}'`
# kubectl -n fy get secret/$TOKENNAME -o jsonpath='{.data.token}' | base64 -d
