name: Build and Deploy

on:
  push:
    branches: [main]

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      # - name: Create kubeconfig volume
      #   shell: bash
      #   run: echo {{ secrets.KUBECONFIG}} > /kubeconfig/conf.yaml
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          network: host
          tags: ghcr.io/${{ github.repository }}:${{ github.ref_name	}}, ghcr.io/${{ github.repository }}:${{ github.sha }}
          build-args: |
            DATABASE_URL=${{ secrets.DATABASE_URL }}
    services:
      db:
        image: ghcr.io/ludusrusso/kubectl-with-env-config:a9715de7bace8ca5e8fefc57f3a80ce18337be56
        env:
          KUBECONFIG: "${{ secrets.KUBECONFIG }}"
          NAMESPACE: "${{ secrets.NAMESPACE }}"
          POD: "${{ secrets.POD }}"
          PORTS: 5432:5432
        ports:
          - 5432:5432
