name: Build and Deploy

on:
  push:
    branches: [main]

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      # - name: Create kubeconfig volume
      #   shell: bash
      #   run: echo {{ secrets.KUBECONFIG}} > /kubeconfig/conf.yaml
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.ref_name	}}, ghcr.io/${{ github.repository }}:${{ github.sha }}
    services:
      db:
        image: ghcr.io/ludusrusso/kubectl-with-env-config:07caab849ed8f24e29f6523a8ae1ac8c31b4ac2a
        args: port-forward -n fy db-postgresql-0 5433:5432 --kubeconfig ./kubeconfig/conf.yaml
        env:
          KUBECONFIG: "{{ secrets.KUBECONFIG }}"
        ports:
          - 5433:5433
