name: Build and Deploy

on:
  push:
    branches: [main]

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.ref_name	}}, ghcr.io/${{ github.repository }}:${{ github.sha }}
    services:
      db:
        image: bitnami/kubectl
        run:
          - echo {{ secrets.KUBECONFIG }} | baase64 -d > ./kubeconfig
          - kubectl port-forward -n fy db-postgresql-0 5433:5432 --kubeconfig ./kubeconfig
        ports:
          - 5433:5433
